name: CD Francisco Javier Melero Lopez

on:
  workflow_dispatch:

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Docker version
        run: docker -v

      - name: Construyendo una imagen
        working-directory: ./hangman-api
        run: docker build -t franciscomelerolopez/hangman-api-franciscomelero:latest .