name: Integración continua Práctica 3 Obligatoria Francisco Melero Lopez

on:
  push:
      branches:  [ master ]
      paths: [ 'hangman-front/**' ]
  pull_request:
      branches:  [ master ]
      paths: [ 'hangman-front/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4  
        with:
          node-version: 18
      - name: Build
        working-directory: ./hangman-front
        run: |
           npm ci
            npm run build
  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v4  
        with:
          node-version: 18
      - name: test
        working-directory: ./hangman-front
        run: |
           npm ci
           npm run test
  bye:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ always() }}
    steps:
      - name: Bye
        run: echo "Hasta luego Francisco Melero a la tarea número 1 de la práctica GitHub"
